site_name: TBT个人网站
site_url: https://tianbaiting.github.io/

theme:
  name: material
  language: zh  # 中文，解决中文搜索问题
  custom_dir: overrides
  palette:
    # 亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    # 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - tabs
    - content.tabs.link
    - search.highlight
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - search.share


markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true  # 启用行号
  - attr_list
  - pymdownx.tabbed
  - nl2br
  - toc:
      permalink: '#'
      slugify: !!python/name:pymdownx.slugs.uslugify
  - admonition
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_files:
  - docs/google0ec64d869ee59589.html
  - docs/robots.txt

plugins:
  - search
  - roamlinks
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css