site_name: TBT个人网站
site_url: https://tianbaiting.github.io/ 
theme:
  name: material
  language: zh  # 中文，解决中文搜索问题
  features:
    - navigation.expand 
    - tabs 

markdown_extensions: 
  - attr_list
  - pymdownx.tabbed
  - nl2br
  - toc:
      permalink: '#'
  - pymdownx.slugs
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_files:
  - docs/google0ec64d869ee59589.html
  - docs/robots.txt
  
plugins:
  - search
  - roamlinks
  - sitemap:  # 添加这一部分
      sitemap_url: https://tianbaiting.github.io/
      priority: 0.8  # 可选：页面优先级
      changefreq: weekly  # 可选：更新频率
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css