site_name: TBT个人网站
site_url: https://tianbaiting.github.io/

theme:
  name: material
  language: zh  # 中文，解决中文搜索问题
  custom_dir: overrides
  palette:
    primary: 'indigo'
    accent: 'pink'
    scheme: 'default'  # default, slate, solarized-light, solarized-dark
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.expand
    - tabs
    - content.tabs.link
    - search.highlight
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - search.share


markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true  # 启用行号
  - attr_list
  - pymdownx.tabbed
  - nl2br
  - toc:
      permalink: '#'
      slugify: !!python/name:pymdownx.slugs.uslugify
  - admonition
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# extra_files:
#   - docs/google0ec64d869ee59589.html
#   - docs/robots.txt

plugins:
  - search
  - roamlinks
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - js/scheme.js
  

extra_css:
  - css/counter.css

# nav:
#   - 首页: index.md  # 顶部和侧边栏
#   - 指南:  # 顶部和侧边栏（下拉菜单）
#     - 入门: guide/getting-started.md  # 仅侧边栏
#     - 高级用法: guide/advanced-usage.md  # 仅侧边栏
#   - 联系方式: contact.md  # 顶部和侧边栏
#   - 侧边栏专属:  # 仅侧边栏
#     - 页面 A: sidebar/page-a.md  # 仅侧边栏
#     - 页面 B: sidebar/page-b.md  # 仅侧边栏

# nav:
#   - 首页: 
#     - index.md  # 顶部和侧边栏
#     - howtomakewebsite.md
#   - life: 
#   - sci: 
#   - MickeyMiaoMiao: 

