name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install "mkdocs-static-i18n<1.0"
      - name: Generate knowledge graph data
        run: python generate_graph_data.py
      - run: mkdocs gh-deploy --force